export enum Endpoints {
  Actions      = 'actions'      ,
  Activity     = 'activity'     ,
  Apps         = 'apps'         ,
  Checks       = 'checks'       ,
  CodeScanning = 'code-scanning',
  Emojis       = 'emojis'       ,
  Git          = 'git'          ,
  Gitignore    = 'gitignore'    ,
  Interactions = 'interactions' ,
  Issues       = 'issues'       ,
  Licenses     = 'licenses'     ,
  Markdown     = 'markdown'     ,
  Meta         = 'meta'         ,
  Migrations   = 'migrations'   ,
  Orgs         = 'orgs'         ,
  Projects     = 'projects'     ,
  Pulls        = 'pulls'        ,
  Reactions    = 'reactions'    ,
  Repos        = 'repos'        ,
  Scim         = 'scim'         ,
  Search       = 'search'       ,
  Teams        = 'teams'        ,
  Users        = 'users'
}
